const IDR=new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0});
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const DEFAULT_SETTINGS={nightlyRate:3500000,serviceRate:.05,taxRate:0};
function parse(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function reservations(){return parse('zuzu_reservations',[])}
function expenses(){return parse('zuzu_expenses',[])}
function ads(){return parse('zuzu_ads',{meta:0,instagram:0,google:0})}
function settings(){return parse('zuzu_settings',DEFAULT_SETTINGS)}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmtDate(v){if(!v)return '—';return new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'2-digit'}).format(new Date(v+'T00:00:00'))}
function monthKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function statusClass(v){return String(v||'Pending').toLowerCase()}
function totalExpenses(){return expenses().reduce((a,b)=>a+Number(b.amount||0),0)}
function totalAds(){const a=ads();return Number(a.meta||0)+Number(a.instagram||0)+Number(a.google||0)}
function paidRevenue(){return reservations().filter(x=>x.status==='Paid').reduce((a,b)=>a+Number(b.total||0),0)}
function pendingRevenue(){return reservations().filter(x=>x.status==='Pending').reduce((a,b)=>a+Number(b.total||0),0)}
function toast(message){const el=$('#toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(window.__zuzuToast);window.__zuzuToast=setTimeout(()=>el.classList.remove('show'),1900)}

const titles={overview:'Business overview',reservations:'Reservations',finance:'Finance',marketing:'Marketing',settings:'Rates & tax'};
function setView(view,updateHash=true){if(!titles[view])view='overview';$$('.admin-view').forEach(el=>el.hidden=el.id!==`view-${view}`);$$('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===view));if($('#viewTitle'))$('#viewTitle').textContent=titles[view];if(updateHash)history.replaceState(null,'',`#${view}`);window.scrollTo({top:0,behavior:'smooth'})}
function setupViews(){$$('[data-view]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();setView(el.dataset.view)}));$$('[data-go]').forEach(el=>el.addEventListener('click',()=>setView(el.dataset.go)));setView(location.hash.replace('#','')||'overview',false)}

function isoDate(base,offset){const d=new Date(base);d.setHours(12,0,0,0);d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function demoBooking({id,name,email,phone,offset,nights,guests,status,source,campaign}){const base=new Date(),checkin=isoDate(base,offset),checkout=isoDate(base,offset+nights),created=isoDate(base,Math.min(offset-8,-1));const subtotal=nights*DEFAULT_SETTINGS.nightlyRate,service=subtotal*DEFAULT_SETTINGS.serviceRate,tax=0;return{id,createdAt:`${created}T08:00:00.000Z`,name,email,phone,notes:'Presentation sample',checkin,checkout,guests,nights,subtotal,service,tax,total:subtotal+service+tax,status,source,campaign,demo:true}}
function buildDemoReservations(){return[
  demoBooking({id:'DEMO-ZUZU-106',name:'Sofia Romano',email:'sofia@example.com',phone:'+39 000 000 106',offset:22,nights:3,guests:2,status:'Pending',source:'Google',campaign:'Bali Family Stay'}),
  demoBooking({id:'DEMO-ZUZU-105',name:'Luca & Sofia',email:'luca@example.com',phone:'+39 000 000 105',offset:9,nights:4,guests:4,status:'Pending',source:'Instagram',campaign:'Pererenan Escape'}),
  demoBooking({id:'DEMO-ZUZU-104',name:'Chloe Martin',email:'chloe@example.com',phone:'+33 000 000 104',offset:-12,nights:5,guests:3,status:'Paid',source:'Meta',campaign:'Direct Bali Stay'}),
  demoBooking({id:'DEMO-ZUZU-103',name:'Raka Pratama',email:'raka@example.com',phone:'+62 800 0000 103',offset:-27,nights:2,guests:2,status:'Paid',source:'Direct',campaign:''}),
  demoBooking({id:'DEMO-ZUZU-102',name:'Olivia Hart',email:'olivia@example.com',phone:'+61 400 000 102',offset:-49,nights:3,guests:2,status:'Paid',source:'Google',campaign:'Bali Private House'}),
  demoBooking({id:'DEMO-ZUZU-101',name:'Maya & Daniel',email:'maya@example.com',phone:'+44 7000 000101',offset:-74,nights:4,guests:4,status:'Paid',source:'Instagram',campaign:'Pererenan Family'}),
  demoBooking({id:'DEMO-ZUZU-100',name:'Adrian Lee',email:'adrian@example.com',phone:'+65 8000 0100',offset:15,nights:2,guests:2,status:'Cancelled',source:'Meta',campaign:'Bali Weekender'})
]}
function loadDemoData(announce=true){const current=reservations(),demo=buildDemoReservations(),ids=new Set(current.map(x=>x.id)),merged=[...demo.filter(x=>!ids.has(x.id)),...current];localStorage.setItem('zuzu_reservations',JSON.stringify(merged));if(!localStorage.getItem('zuzu_settings'))localStorage.setItem('zuzu_settings',JSON.stringify(DEFAULT_SETTINGS));const currentExpenses=expenses();if(!currentExpenses.length)localStorage.setItem('zuzu_expenses',JSON.stringify([{date:isoDate(new Date(),-18),category:'Housekeeping & laundry',amount:2400000,demo:true},{date:isoDate(new Date(),-31),category:'Property maintenance',amount:1750000,demo:true},{date:isoDate(new Date(),-9),category:'Guest supplies',amount:1200000,demo:true}]));const a=ads();if(!Number(a.meta||0)&&!Number(a.instagram||0)&&!Number(a.google||0))localStorage.setItem('zuzu_ads',JSON.stringify({meta:2200000,instagram:1400000,google:1600000,demo:true}));localStorage.setItem('zuzu_demo_loaded','1');render();if(announce)toast('Presentation demo loaded')}
function ensurePresentationData(){if(!reservations().length)loadDemoData(false)}

function renderChart(){const now=new Date(),months=[];for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);months.push({key:monthKey(d),label:new Intl.DateTimeFormat('en',{month:'short'}).format(d),value:0})}reservations().filter(r=>r.status==='Paid').forEach(r=>{const source=String(r.checkin||r.createdAt||'').slice(0,7),m=months.find(x=>x.key===source);if(m)m.value+=Number(r.total||0)});const max=Math.max(...months.map(x=>x.value),1),chart=$('#revenueChart');if(!chart)return;chart.innerHTML=months.map(m=>`<div class="chart-col"><div class="chart-value">${m.value?IDR.format(m.value):'—'}</div><div class="chart-bar-track"><div class="chart-bar" style="height:${m.value?Math.max(10,Math.round(m.value/max*100)):4}%"></div></div><span>${m.label}</span></div>`).join('')}
function sortedReservations(){return reservations().slice().sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')))}
function renderRecent(){const box=$('#recentReservations');if(!box)return;const items=sortedReservations().slice(0,4);box.innerHTML=items.length?items.map(x=>`<div class="recent-item"><div><strong>${esc(x.name||'Guest')}</strong><small>${esc(x.id||'—')} · ${esc(x.source||'Direct')}</small></div><div><small>${fmtDate(x.checkin)} → ${fmtDate(x.checkout)}</small><span class="status-pill ${statusClass(x.status)}">${esc(x.status||'Pending')}</span></div><div class="recent-total">${IDR.format(Number(x.total||0))}</div></div>`).join(''):'<div class="empty-state"><strong>No reservation activity yet</strong><span>New guest requests from the website will appear here.</span></div>'}
function renderReservations(){const all=sortedReservations(),q=String($('#reservationSearch')?.value||'').trim().toLowerCase(),filter=$('#reservationFilter')?.value||'All';const rows=all.filter(x=>{const hay=[x.id,x.name,x.email,x.source,x.campaign].join(' ').toLowerCase();return(!q||hay.includes(q))&&(filter==='All'||x.status===filter)});if($('#reservationCount'))$('#reservationCount').textContent=`${rows.length} of ${all.length} records`;const tbody=$('#reservationRows');if(!tbody)return;tbody.innerHTML=rows.length?rows.map(x=>`<tr><td data-label="Reference"><strong>${esc(x.id)}</strong><small>${x.demo?'Demo · ':''}${fmtDate(String(x.createdAt||'').slice(0,10))}</small></td><td data-label="Guest">${esc(x.name||'—')}<small>${esc(x.email||'')}</small></td><td data-label="Stay">${fmtDate(x.checkin)}<small>to ${fmtDate(x.checkout)}</small></td><td data-label="Guests">${esc(x.guests||'—')}</td><td data-label="Total"><strong>${IDR.format(Number(x.total||0))}</strong></td><td data-label="Source">${esc(x.source||'Direct')}</td><td data-label="Status"><select class="status-select ${statusClass(x.status)}" onchange="setStatus('${esc(x.id)}',this.value)"><option ${x.status==='Pending'?'selected':''}>Pending</option><option ${x.status==='Paid'?'selected':''}>Paid</option><option ${x.status==='Cancelled'?'selected':''}>Cancelled</option></select></td></tr>`).join(''):'<tr><td colspan="7"><div class="empty-state"><strong>No matching reservations</strong><span>Try another search or status filter.</span></div></td></tr>'}
function renderExpenses(){const list=$('#expenseList');if(!list)return;const items=expenses().slice().reverse().slice(0,8);list.innerHTML=items.length?items.map(x=>`<div class="expense-item"><div><strong>${esc(x.category)}</strong><span>${fmtDate(x.date)}${x.demo?' · demo':''}</span></div><b>${IDR.format(Number(x.amount||0))}</b></div>`).join(''):'<div class="empty-row">No operating expenses logged yet.</div>'}
function render(){const r=reservations(),gross=paidRevenue(),exp=totalExpenses(),ad=totalAds(),net=gross-exp-ad,roas=ad?gross/ad:0,pending=r.filter(x=>x.status==='Pending').length,paid=r.filter(x=>x.status==='Paid').length,s=settings(),a=ads();
  if($('#kGross'))$('#kGross').textContent=IDR.format(gross);if($('#kNet'))$('#kNet').textContent=IDR.format(net);if($('#kPending'))$('#kPending').textContent=IDR.format(pendingRevenue());if($('#kRoas'))$('#kRoas').textContent=roas?roas.toFixed(1)+'×':'—';
  if($('#kPaidCount'))$('#kPaidCount').textContent=paid;if($('#kPendingCount'))$('#kPendingCount').textContent=pending;if($('#kNightly'))$('#kNightly').textContent=IDR.format(Number(s.nightlyRate||0));
  if($('#metaSpend'))$('#metaSpend').textContent=IDR.format(Number(a.meta||0));if($('#igSpend'))$('#igSpend').textContent=IDR.format(Number(a.instagram||0));if($('#googleSpend'))$('#googleSpend').textContent=IDR.format(Number(a.google||0));
  if($('#financeGross'))$('#financeGross').textContent=IDR.format(gross);if($('#financeAds'))$('#financeAds').textContent=IDR.format(ad);if($('#financeExpenses'))$('#financeExpenses').textContent=IDR.format(exp);if($('#financeNet'))$('#financeNet').textContent=IDR.format(net);
  if($('#nightlyRate'))$('#nightlyRate').value=s.nightlyRate;if($('#serviceRate'))$('#serviceRate').value=s.serviceRate*100;if($('#taxRate'))$('#taxRate').value=s.taxRate*100;
  const af=$('#adsForm');if(af){af.elements.meta.value=a.meta||0;af.elements.instagram.value=a.instagram||0;af.elements.google.value=a.google||0}
  if($('#reportPeriod'))$('#reportPeriod').textContent=`Updated ${new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date())} · presentation preview`;
  renderChart();renderRecent();renderReservations();renderExpenses()
}
function setStatus(id,status){const list=reservations(),x=list.find(r=>r.id===id);if(x)x.status=status;localStorage.setItem('zuzu_reservations',JSON.stringify(list));render();toast(`Reservation marked ${status}`)}
function saveExpense(e){e.preventDefault();const f=new FormData(e.target),list=expenses();list.push({date:f.get('date'),category:String(f.get('category')||'').trim(),amount:Number(f.get('amount'))||0,demo:false});localStorage.setItem('zuzu_expenses',JSON.stringify(list));e.target.reset();render();toast('Expense added')}
function saveAds(e){e.preventDefault();const f=new FormData(e.target);localStorage.setItem('zuzu_ads',JSON.stringify({meta:Number(f.get('meta'))||0,instagram:Number(f.get('instagram'))||0,google:Number(f.get('google'))||0}));render();toast('Marketing spend updated')}
function saveSettings(e){e.preventDefault();const f=new FormData(e.target);localStorage.setItem('zuzu_settings',JSON.stringify({nightlyRate:Number(f.get('nightlyRate'))||DEFAULT_SETTINGS.nightlyRate,serviceRate:(Number(f.get('serviceRate'))||0)/100,taxRate:(Number(f.get('taxRate'))||0)/100}));render();toast('Pricing settings saved')}
function exportCSV(){const rows=[['Booking ID','Created','Guest','Email','Phone','Check-in','Check-out','Guests','Nights','Subtotal','Service','Tax','Total','Status','Source','Campaign','Demo'],...sortedReservations().map(x=>[x.id,x.createdAt,x.name,x.email,x.phone,x.checkin,x.checkout,x.guests,x.nights,x.subtotal,x.service,x.tax,x.total,x.status,x.source,x.campaign,x.demo?'Yes':'No'])];const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');const b=new Blob([csv],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`zuzu-reservations-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(u);toast('CSV exported')}

document.addEventListener('DOMContentLoaded',()=>{ensurePresentationData();setupViews();$('#loadDemoBtn')?.addEventListener('click',()=>loadDemoData(true));$('#expenseForm')?.addEventListener('submit',saveExpense);$('#adsForm')?.addEventListener('submit',saveAds);$('#settingsForm')?.addEventListener('submit',saveSettings);$('#reservationSearch')?.addEventListener('input',renderReservations);$('#reservationFilter')?.addEventListener('change',renderReservations);render()});
