const IDR=new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0});
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const API_BASE=String(window.ZUZU_CONFIG?.apiBase||'').replace(/\/+$/,'');
const state={reservations:[],expenses:[],ads:{meta:0,instagram:0,google:0},settings:{nightlyRate:3500000,serviceRate:.05,taxRate:0},summary:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const token=()=>sessionStorage.getItem('zuzu_admin_token')||'';
const setToken=v=>v?sessionStorage.setItem('zuzu_admin_token',v):sessionStorage.removeItem('zuzu_admin_token');
function fmtDate(v){if(!v)return '—';return new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'2-digit'}).format(new Date(v+'T00:00:00'))}
function statusClass(v){return String(v||'Pending').toLowerCase()}
function toast(message){const el=$('#toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(window.__zuzuToast);window.__zuzuToast=setTimeout(()=>el.classList.remove('show'),2200)}
async function api(path,options={}){if(!API_BASE)throw new Error('Production API is not configured.');const headers={'Content-Type':'application/json',...(options.headers||{})};if(token())headers.Authorization='Bearer '+token();const res=await fetch(API_BASE+path,{...options,headers});let data={};try{data=await res.json()}catch{}if(!res.ok){const e=new Error(data.error||('Request failed ('+res.status+')'));e.status=res.status;throw e}return data}
function normalizeReservation(x){return{id:x.id,createdAt:x.created_at||x.createdAt,updatedAt:x.updated_at||x.updatedAt,name:x.name,email:x.email,phone:x.phone,notes:x.notes||'',checkin:x.checkin,checkout:x.checkout,guests:Number(x.guests||0),nights:Number(x.nights||0),subtotal:Number(x.subtotal||0),service:Number(x.service||0),tax:Number(x.tax||0),total:Number(x.total||0),status:x.status||'Pending',source:x.source||'Direct',campaign:x.campaign||''}}
function showAuth(msg='Enter the owner access token to load live ZUZU data.'){const box=$('#adminAuth');if(box)box.hidden=false;const m=$('#adminAuthMessage');if(m)m.textContent=msg;setTimeout(()=>$('#adminToken')?.focus(),50)}
function hideAuth(){const box=$('#adminAuth');if(box)box.hidden=true}
function handleError(err){if(err?.status===401){setToken('');showAuth('Access denied. Enter the current owner access token.')}else toast(err?.message||'Something went wrong.')}
async function refreshAll(){const [r,s,c,e,a]=await Promise.all([api('/api/admin/reservations'),api('/api/admin/summary'),api('/api/admin/settings'),api('/api/admin/expenses'),api('/api/admin/ads')]);state.reservations=(r.reservations||[]).map(normalizeReservation);state.summary=s.summary||null;state.settings=c.settings||state.settings;state.expenses=(e.expenses||[]).map(x=>({id:x.id,date:x.date,category:x.category,amount:Number(x.amount||0)}));state.ads={meta:Number(a.ads?.meta||0),instagram:Number(a.ads?.instagram||0),google:Number(a.ads?.google||0)};hideAuth();render()}
const titles={overview:'Business overview',reservations:'Reservations',finance:'Finance',marketing:'Marketing',settings:'Rates & tax'};
function setView(view,updateHash=true){if(!titles[view])view='overview';$$('.admin-view').forEach(el=>el.hidden=el.id!=='view-'+view);$$('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===view));if($('#viewTitle'))$('#viewTitle').textContent=titles[view];if(updateHash)history.replaceState(null,'','#'+view);window.scrollTo({top:0,behavior:'smooth'})}
function setupViews(){$$('[data-view]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();setView(el.dataset.view)}));$$('[data-go]').forEach(el=>el.addEventListener('click',()=>setView(el.dataset.go)));setView(location.hash.replace('#','')||'overview',false)}
function sortedReservations(){return state.reservations.slice().sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')))}
function renderChart(){const now=new Date(),months=[];for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);months.push({key:d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0'),label:new Intl.DateTimeFormat('en',{month:'short'}).format(d),value:0})}state.reservations.filter(r=>r.status==='Paid').forEach(r=>{const m=months.find(x=>x.key===String(r.checkin||r.createdAt||'').slice(0,7));if(m)m.value+=Number(r.total||0)});const max=Math.max(...months.map(x=>x.value),1),chart=$('#revenueChart');if(chart)chart.innerHTML=months.map(m=>'<div class="chart-col"><div class="chart-value">'+(m.value?IDR.format(m.value):'—')+'</div><div class="chart-bar-track"><div class="chart-bar" style="height:'+(m.value?Math.max(10,Math.round(m.value/max*100)):4)+'%"></div></div><span>'+m.label+'</span></div>').join('')}
function renderRecent(){const box=$('#recentReservations');if(!box)return;const items=sortedReservations().slice(0,4);box.innerHTML=items.length?items.map(x=>'<div class="recent-item"><div><strong>'+esc(x.name||'Guest')+'</strong><small>'+esc(x.id||'—')+' · '+esc(x.source||'Direct')+'</small></div><div><small>'+fmtDate(x.checkin)+' → '+fmtDate(x.checkout)+'</small><span class="status-pill '+statusClass(x.status)+'">'+esc(x.status)+'</span></div><div class="recent-total">'+IDR.format(x.total)+'</div></div>').join(''):'<div class="empty-state"><strong>No reservation activity yet</strong><span>New website requests will appear here.</span></div>'}
function renderReservations(){const all=sortedReservations(),q=String($('#reservationSearch')?.value||'').trim().toLowerCase(),filter=$('#reservationFilter')?.value||'All';const rows=all.filter(x=>{const hay=[x.id,x.name,x.email,x.source,x.campaign].join(' ').toLowerCase();return(!q||hay.includes(q))&&(filter==='All'||x.status===filter)});if($('#reservationCount'))$('#reservationCount').textContent=rows.length+' of '+all.length+' records';const tbody=$('#reservationRows');if(!tbody)return;tbody.innerHTML=rows.length?rows.map(x=>'<tr><td data-label="Reference"><strong>'+esc(x.id)+'</strong><small>'+fmtDate(String(x.createdAt||'').slice(0,10))+'</small></td><td data-label="Guest">'+esc(x.name||'—')+'<small>'+esc(x.email||'')+'</small></td><td data-label="Stay">'+fmtDate(x.checkin)+'<small>to '+fmtDate(x.checkout)+'</small></td><td data-label="Guests">'+esc(x.guests||'—')+'</td><td data-label="Total"><strong>'+IDR.format(x.total)+'</strong></td><td data-label="Source">'+esc(x.source||'Direct')+'</td><td data-label="Status"><select class="status-select '+statusClass(x.status)+'" onchange="setStatus(\''+esc(x.id)+'\',this.value)"><option '+(x.status==='Pending'?'selected':'')+'>Pending</option><option '+(x.status==='Confirmed'?'selected':'')+'>Confirmed</option><option '+(x.status==='Paid'?'selected':'')+'>Paid</option><option '+(x.status==='Cancelled'?'selected':'')+'>Cancelled</option></select></td></tr>').join(''):'<tr><td colspan="7"><div class="empty-state"><strong>No matching reservations</strong></div></td></tr>'}
function renderExpenses(){const list=$('#expenseList');if(!list)return;const items=state.expenses.slice(0,8);list.innerHTML=items.length?items.map(x=>'<div class="expense-item"><div><strong>'+esc(x.category)+'</strong><span>'+fmtDate(x.date)+'</span></div><b>'+IDR.format(x.amount)+'</b></div>').join(''):'<div class="empty-row">No operating expenses logged yet.</div>'}
function render(){const s=state.summary||{},a=state.ads,c=state.settings;if($('#kGross'))$('#kGross').textContent=IDR.format(Number(s.paidRevenue||0));if($('#kNet'))$('#kNet').textContent=IDR.format(Number(s.netRevenue||0));if($('#kPending'))$('#kPending').textContent=IDR.format(Number(s.pendingValue||0));if($('#kRoas'))$('#kRoas').textContent=Number(s.roas||0)?Number(s.roas).toFixed(1)+'×':'—';if($('#kPaidCount'))$('#kPaidCount').textContent=Number(s.paidCount||0);if($('#kPendingCount'))$('#kPendingCount').textContent=Number(s.pendingCount||0);if($('#kNightly'))$('#kNightly').textContent=IDR.format(Number(c.nightlyRate||0));if($('#financeGross'))$('#financeGross').textContent=IDR.format(Number(s.paidRevenue||0));if($('#financeAds'))$('#financeAds').textContent=IDR.format(Number(s.adSpend||0));if($('#financeExpenses'))$('#financeExpenses').textContent=IDR.format(Number(s.expenses||0));if($('#financeNet'))$('#financeNet').textContent=IDR.format(Number(s.netRevenue||0));if($('#metaSpend'))$('#metaSpend').textContent=IDR.format(a.meta);if($('#igSpend'))$('#igSpend').textContent=IDR.format(a.instagram);if($('#googleSpend'))$('#googleSpend').textContent=IDR.format(a.google);if($('#nightlyRate'))$('#nightlyRate').value=c.nightlyRate;if($('#serviceRate'))$('#serviceRate').value=Number(c.serviceRate||0)*100;if($('#taxRate'))$('#taxRate').value=Number(c.taxRate||0)*100;const af=$('#adsForm');if(af){af.elements.meta.value=a.meta;af.elements.instagram.value=a.instagram;af.elements.google.value=a.google}if($('#reportPeriod'))$('#reportPeriod').textContent='Live production data · '+new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date());renderChart();renderRecent();renderReservations();renderExpenses()}
async function setStatus(id,status){try{await api('/api/admin/reservations/'+encodeURIComponent(id)+'/status',{method:'PATCH',body:JSON.stringify({status})});await refreshAll();toast('Reservation marked '+status)}catch(e){handleError(e);await refreshAll().catch(()=>{})}}
async function saveExpense(e){e.preventDefault();const f=new FormData(e.target);try{await api('/api/admin/expenses',{method:'POST',body:JSON.stringify({date:f.get('date'),category:String(f.get('category')||'').trim(),amount:Number(f.get('amount'))||0})});e.target.reset();await refreshAll();toast('Expense added')}catch(err){handleError(err)}}
async function saveAds(e){e.preventDefault();const f=new FormData(e.target);try{await api('/api/admin/ads',{method:'PUT',body:JSON.stringify({meta:Number(f.get('meta'))||0,instagram:Number(f.get('instagram'))||0,google:Number(f.get('google'))||0})});await refreshAll();toast('Marketing spend updated')}catch(err){handleError(err)}}
async function saveSettings(e){e.preventDefault();const f=new FormData(e.target);try{await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({nightlyRate:Number(f.get('nightlyRate')),serviceRate:Number(f.get('serviceRate'))/100,taxRate:Number(f.get('taxRate'))/100})});await refreshAll();toast('Pricing settings saved')}catch(err){handleError(err)}}
function exportCSV(){const rows=[['Booking ID','Created','Guest','Email','Phone','Check-in','Check-out','Guests','Nights','Subtotal','Service','Tax','Total','Status','Source','Campaign'],...sortedReservations().map(x=>[x.id,x.createdAt,x.name,x.email,x.phone,x.checkin,x.checkout,x.guests,x.nights,x.subtotal,x.service,x.tax,x.total,x.status,x.source,x.campaign])];const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');const b=new Blob([csv],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='zuzu-reservations-'+new Date().toISOString().slice(0,10)+'.csv';a.click();URL.revokeObjectURL(u)}
document.addEventListener('DOMContentLoaded',()=>{setupViews();$('#expenseForm')?.addEventListener('submit',saveExpense);$('#adsForm')?.addEventListener('submit',saveAds);$('#settingsForm')?.addEventListener('submit',saveSettings);$('#reservationSearch')?.addEventListener('input',renderReservations);$('#reservationFilter')?.addEventListener('change',renderReservations);$('#adminAuthForm')?.addEventListener('submit',async e=>{e.preventDefault();const v=String($('#adminToken')?.value||'').trim();if(!v)return;setToken(v);try{await refreshAll();$('#adminToken').value=''}catch(err){handleError(err)}});$('#logoutBtn')?.addEventListener('click',()=>{setToken('');showAuth('Signed out. Enter the owner access token to continue.')});if(token())refreshAll().catch(handleError);else showAuth()});
