const IDR=new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0});
const DEFAULT_SETTINGS={nightlyRate:3500000,serviceRate:.05,taxRate:0};
const $=s=>document.querySelector(s);
function safeParse(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function getSettings(){return safeParse('zuzu_settings',DEFAULT_SETTINGS)}
function nightsBetween(a,b){if(!a||!b)return 0;const d1=new Date(a+'T00:00:00'),d2=new Date(b+'T00:00:00');return Math.max(0,Math.round((d2-d1)/86400000))}
function fmtDate(v){return v?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(v+'T00:00:00')):''}
function updateDatePlaceholders(){['#checkin','#checkout'].forEach(sel=>{const el=$(sel);el?.closest('.date-input-wrap')?.classList.toggle('has-value',Boolean(el.value))})}
function syncModalDatesFromMain(){if($('#modalCheckin'))$('#modalCheckin').value=$('#checkin')?.value||'';if($('#modalCheckout'))$('#modalCheckout').value=$('#checkout')?.value||'';syncCheckoutMin('#modalCheckin','#modalCheckout')}
function syncMainDatesFromModal(){if($('#checkin'))$('#checkin').value=$('#modalCheckin')?.value||'';if($('#checkout'))$('#checkout').value=$('#modalCheckout')?.value||'';syncCheckoutMin('#checkin','#checkout');updateDatePlaceholders()}
function updateSummary(){const ci=$('#modalCheckin')?.value||$('#checkin')?.value||'',co=$('#modalCheckout')?.value||$('#checkout')?.value||'',guests=Number($('#guests')?.value||2),s=getSettings(),nights=nightsBetween(ci,co),subtotal=nights*s.nightlyRate,service=subtotal*s.serviceRate,tax=(subtotal+service)*s.taxRate,total=subtotal+service+tax;const vals={sumNights:nights?`${nights} night${nights===1?'':'s'}`:'—',sumGuests:`${guests} guest${guests===1?'':'s'}`,sumSubtotal:IDR.format(subtotal),sumService:IDR.format(service),sumTax:IDR.format(tax),sumTotal:IDR.format(total)};Object.entries(vals).forEach(([id,v])=>{const e=document.getElementById(id);if(e)e.textContent=v});const stay=$('#selectedStay strong');if(stay)stay.textContent=ci&&co&&nights?`${fmtDate(ci)} — ${fmtDate(co)} · ${guests} guest${guests===1?'':'s'}`:'Select check-in and check-out dates';updateDatePlaceholders();return{ci,co,guests,nights,subtotal,service,tax,total}}
function setDateLimits(){const d=new Date();d.setHours(0,0,0,0);const min=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;['#checkin','#checkout','#modalCheckin','#modalCheckout'].forEach(sel=>$(sel)?.setAttribute('min',min))}
function syncCheckoutMin(ciSel='#checkin',coSel='#checkout'){const ci=$(ciSel)?.value,co=$(coSel);if(!ci||!co)return;const d=new Date(ci+'T00:00:00');d.setDate(d.getDate()+1);const v=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;co.setAttribute('min',v);if(co.value&&co.value<v)co.value=''}
function openModal(){syncModalDatesFromMain();const m=$('#bookingModal');if(!m)return;m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');updateSummary();setTimeout(()=>{const target=$('#modalCheckin')?.value?$('#guestName'):$('#modalCheckin');target?.focus()},120)}
function closeModal(){const m=$('#bookingModal');if(!m)return;m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
function setupMenu(){const b=$('#menuToggle'),m=$('#mobileMenu');if(!b||!m)return;b.addEventListener('click',()=>{const open=m.classList.toggle('open');b.classList.toggle('open',open);b.setAttribute('aria-expanded',String(open))});m.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{m.classList.remove('open');b.classList.remove('open');b.setAttribute('aria-expanded','false')}))}
function setupModal(){document.querySelectorAll('.reserve-trigger').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();openModal()}));document.querySelectorAll('[data-close-modal]').forEach(el=>el.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()})}
function setupFaq(){document.querySelectorAll('.faq details').forEach(d=>d.addEventListener('toggle',()=>{if(!d.open)return;document.querySelectorAll('.faq details').forEach(o=>{if(o!==d)o.open=false})}))}
function saveBooking(e){e.preventDefault();syncMainDatesFromModal();const x=updateSummary(),notice=$('#bookingNotice'),success=$('#bookingSuccess');if(x.nights<1){notice.textContent='Please select valid check-in and check-out dates.';notice.classList.add('show');success.classList.remove('show');return}notice.classList.remove('show');const f=new FormData(e.target),q=new URLSearchParams(location.search),booking={id:'ZUZU-'+Date.now().toString().slice(-7),createdAt:new Date().toISOString(),name:String(f.get('name')||'').trim(),email:String(f.get('email')||'').trim(),phone:String(f.get('phone')||'').trim(),notes:String(f.get('notes')||'').trim(),checkin:x.ci,checkout:x.co,guests:x.guests,nights:x.nights,subtotal:x.subtotal,service:x.service,tax:x.tax,total:x.total,status:'Pending',source:q.get('utm_source')||'Direct',campaign:q.get('utm_campaign')||''};const list=safeParse('zuzu_reservations',[]);list.unshift(booking);localStorage.setItem('zuzu_reservations',JSON.stringify(list));success.innerHTML=`Reservation request created.<br><strong>Reference ${booking.id}</strong>`;success.classList.add('show');e.target.reset();syncModalDatesFromMain();updateSummary()}
document.addEventListener('DOMContentLoaded',()=>{setDateLimits();setupMenu();setupModal();setupFaq();const y=$('#year');if(y)y.textContent=new Date().getFullYear();$('#checkin')?.addEventListener('change',()=>{syncCheckoutMin('#checkin','#checkout');syncModalDatesFromMain();updateSummary()});$('#checkout')?.addEventListener('change',()=>{syncModalDatesFromMain();updateSummary()});$('#guests')?.addEventListener('change',updateSummary);$('#modalCheckin')?.addEventListener('change',()=>{syncCheckoutMin('#modalCheckin','#modalCheckout');syncMainDatesFromModal();updateSummary()});$('#modalCheckout')?.addEventListener('change',()=>{syncMainDatesFromModal();updateSummary()});$('#checkAvailability')?.addEventListener('click',()=>{const x=updateSummary();if(x.nights<1){document.getElementById('availability')?.scrollIntoView({behavior:'smooth'});return}openModal()});$('#bookingForm')?.addEventListener('submit',saveBooking);updateSummary()});
