const IDR=new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0});
const DEFAULT_SETTINGS={nightlyRate:3500000,serviceRate:.05,taxRate:0};
const API_BASE=String(window.ZUZU_CONFIG?.apiBase||'').replace(/\/+$/,'');
let remoteSettings=null;
let remoteQuote=null;
const $=s=>document.querySelector(s);
function safeParse(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function getSettings(){return remoteSettings||safeParse('zuzu_settings',DEFAULT_SETTINGS)}
async function api(path,options={}){if(!API_BASE)throw new Error('Production API is not configured.');const res=await fetch(API_BASE+path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});let data={};try{data=await res.json()}catch{}if(!res.ok)throw new Error(data.error||`Request failed (${res.status})`);return data}
async function loadRemoteSettings(){if(!API_BASE)return;try{const data=await api('/api/public/settings');if(data.settings){remoteSettings=data.settings;updateSummary()}}catch(err){console.warn('ZUZU API settings unavailable',err)}}
async function loadRemoteQuote(ci,co){if(!API_BASE||!ci||!co||nightsBetween(ci,co)<1){remoteQuote=null;return null}try{const data=await api(`/api/availability?checkin=${encodeURIComponent(ci)}&checkout=${encodeURIComponent(co)}`);remoteQuote=data.available?{ci,co,...data.quote}:null;return data}catch(err){console.warn('ZUZU API availability unavailable',err);return null}}
function nightsBetween(a,b){if(!a||!b)return 0;const d1=new Date(a+'T00:00:00'),d2=new Date(b+'T00:00:00');return Math.max(0,Math.round((d2-d1)/86400000))}
function fmtDate(v){return v?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(v+'T00:00:00')):''}
function updateDatePlaceholders(){['#checkin','#checkout'].forEach(sel=>{const el=$(sel);el?.closest('.date-input-wrap')?.classList.toggle('has-value',Boolean(el.value))})}
function ensureModalGuests(){const grid=$('#bookingForm .form-grid');if(!grid||$('#modalGuests'))return;const field=document.createElement('div');field.className='field';field.innerHTML='<label for="modalGuests">Guests</label><select id="modalGuests" aria-label="Number of guests"><option value="1">1 guest</option><option value="2">2 guests</option><option value="3">3 guests</option><option value="4">4 guests</option><option value="5">5 guests</option><option value="6">6 guests</option></select>';const fullName=$('#guestName')?.closest('.field');grid.insertBefore(field,fullName||null);if(!$('#modalGuestStyle')){const style=document.createElement('style');style.id='modalGuestStyle';style.textContent='.booking-form #modalGuests{width:100%;height:46px;border:1px solid var(--line);border-radius:10px;padding:0 11px;background:#fff;color:var(--ink);font-weight:600;font-size:13px;outline:none}';document.head.appendChild(style)}}
function syncModalDatesFromMain(){ensureModalGuests();if($('#modalCheckin'))$('#modalCheckin').value=$('#checkin')?.value||'';if($('#modalCheckout'))$('#modalCheckout').value=$('#checkout')?.value||'';if($('#modalGuests'))$('#modalGuests').value=$('#guests')?.value||'2';syncCheckoutMin('#modalCheckin','#modalCheckout')}
function syncMainDatesFromModal(){if($('#checkin'))$('#checkin').value=$('#modalCheckin')?.value||'';if($('#checkout'))$('#checkout').value=$('#modalCheckout')?.value||'';if($('#guests')&&$('#modalGuests'))$('#guests').value=$('#modalGuests').value||'2';syncCheckoutMin('#checkin','#checkout');updateDatePlaceholders()}
function updateSummary(){const ci=$('#modalCheckin')?.value||$('#checkin')?.value||'',co=$('#modalCheckout')?.value||$('#checkout')?.value||'',guests=Number($('#modalGuests')?.value||$('#guests')?.value||2),s=getSettings(),baseNights=nightsBetween(ci,co),rq=remoteQuote&&remoteQuote.ci===ci&&remoteQuote.co===co?remoteQuote:null,nights=rq?.nights??baseNights,subtotal=rq?.subtotal??(nights*s.nightlyRate),service=rq?.service??(subtotal*s.serviceRate),tax=rq?.tax??((subtotal+service)*s.taxRate),total=rq?.total??(subtotal+service+tax);const vals={sumNights:nights?`${nights} night${nights===1?'':'s'}`:'—',sumGuests:`${guests} guest${guests===1?'':'s'}`,sumSubtotal:IDR.format(subtotal),sumService:IDR.format(service),sumTax:IDR.format(tax),sumTotal:IDR.format(total)};Object.entries(vals).forEach(([id,v])=>{const e=document.getElementById(id);if(e)e.textContent=v});const stay=$('#selectedStay strong');if(stay)stay.textContent=ci&&co&&nights?`${fmtDate(ci)} — ${fmtDate(co)} · ${guests} guest${guests===1?'':'s'}`:'Select check-in and check-out dates';updateDatePlaceholders();return{ci,co,guests,nights,subtotal,service,tax,total}}
function setDateLimits(){const d=new Date();d.setHours(0,0,0,0);const min=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;['#checkin','#checkout','#modalCheckin','#modalCheckout'].forEach(sel=>$(sel)?.setAttribute('min',min))}
function syncCheckoutMin(ciSel='#checkin',coSel='#checkout'){const ci=$(ciSel)?.value,co=$(coSel);if(!ci||!co)return;const d=new Date(ci+'T00:00:00');d.setDate(d.getDate()+1);const v=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;co.setAttribute('min',v);if(co.value&&co.value<v)co.value=''}
function openModal(){syncModalDatesFromMain();const m=$('#bookingModal');if(!m)return;m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');updateSummary();setTimeout(()=>{const target=$('#modalCheckin')?.value?$('#guestName'):$('#modalCheckin');target?.focus()},120)}
function closeModal(){const m=$('#bookingModal');if(!m)return;m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
function setupMenu(){const b=$('#menuToggle'),m=$('#mobileMenu');if(!b||!m)return;b.addEventListener('click',()=>{const open=m.classList.toggle('open');b.classList.toggle('open',open);b.setAttribute('aria-expanded',String(open))});m.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{m.classList.remove('open');b.classList.remove('open');b.setAttribute('aria-expanded','false')}))}
function setupModal(){document.querySelectorAll('.reserve-trigger').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();openModal()}));document.querySelectorAll('[data-close-modal]').forEach(el=>el.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()})}
function setupFaq(){document.querySelectorAll('.faq details').forEach(d=>d.addEventListener('toggle',()=>{if(!d.open)return;document.querySelectorAll('.faq details').forEach(o=>{if(o!==d)o.open=false})}))}
async function saveBooking(e){e.preventDefault();syncMainDatesFromModal();const x=updateSummary(),notice=$('#bookingNotice'),success=$('#bookingSuccess');if(x.nights<1){notice.textContent='Please select valid check-in and check-out dates.';notice.classList.add('show');success.classList.remove('show');return}notice.classList.remove('show');const f=new FormData(e.target),q=new URLSearchParams(location.search),booking={id:'ZUZU-'+Date.now().toString().slice(-7),createdAt:new Date().toISOString(),name:String(f.get('name')||'').trim(),email:String(f.get('email')||'').trim(),phone:String(f.get('phone')||'').trim(),notes:String(f.get('notes')||'').trim(),checkin:x.ci,checkout:x.co,guests:x.guests,nights:x.nights,subtotal:x.subtotal,service:x.service,tax:x.tax,total:x.total,status:'Pending',source:q.get('utm_source')||'Direct',campaign:q.get('utm_campaign')||''};try{if(API_BASE){const result=await api('/api/reservations',{method:'POST',body:JSON.stringify(booking)});booking={...booking,...result.reservation}}else{const list=safeParse('zuzu_reservations',[]);list.unshift(booking);localStorage.setItem('zuzu_reservations',JSON.stringify(list))}success.innerHTML=`Reservation request created.<br><strong>Reference ${booking.id}</strong>`;success.classList.add('show');e.target.reset();remoteQuote=null;syncModalDatesFromMain();updateSummary()}catch(err){notice.textContent=err.message||'Unable to create reservation right now.';notice.classList.add('show');success.classList.remove('show')}}
document.addEventListener('DOMContentLoaded',()=>{ensureModalGuests();setDateLimits();setupMenu();setupModal();setupFaq();syncModalDatesFromMain();loadRemoteSettings();const y=$('#year');if(y)y.textContent=new Date().getFullYear();$('#checkin')?.addEventListener('change',async()=>{syncCheckoutMin('#checkin','#checkout');syncModalDatesFromMain();remoteQuote=null;updateSummary();await loadRemoteQuote($('#checkin').value,$('#checkout')?.value||'');updateSummary()});$('#checkout')?.addEventListener('change',async()=>{syncModalDatesFromMain();remoteQuote=null;updateSummary();await loadRemoteQuote($('#checkin')?.value||'',$('#checkout').value);updateSummary()});$('#guests')?.addEventListener('change',()=>{if($('#modalGuests'))$('#modalGuests').value=$('#guests').value;updateSummary()});$('#modalCheckin')?.addEventListener('change',async()=>{syncCheckoutMin('#modalCheckin','#modalCheckout');syncMainDatesFromModal();remoteQuote=null;updateSummary();await loadRemoteQuote($('#modalCheckin').value,$('#modalCheckout')?.value||'');updateSummary()});$('#modalCheckout')?.addEventListener('change',async()=>{syncMainDatesFromModal();remoteQuote=null;updateSummary();await loadRemoteQuote($('#modalCheckin')?.value||'',$('#modalCheckout').value);updateSummary()});$('#modalGuests')?.addEventListener('change',()=>{if($('#guests'))$('#guests').value=$('#modalGuests').value;updateSummary()});$('#checkAvailability')?.addEventListener('click',async()=>{const x=updateSummary();if(x.nights<1){document.getElementById('availability')?.scrollIntoView({behavior:'smooth'});return}if(API_BASE){const result=await loadRemoteQuote(x.ci,x.co);updateSummary();if(result&&!result.available){openModal();const notice=$('#bookingNotice');if(notice){notice.textContent='Those dates are not available. Please choose different dates.';notice.classList.add('show')}return}}openModal()});$('#bookingForm')?.addEventListener('submit',saveBooking);updateSummary()});
