name = "zuzu-production-api"
main = "backend/worker.js"
compatibility_date = "2026-09-01"
workers_dev = true

[vars]
ALLOWED_ORIGIN = "https://zuzu.nadmo.id"

[[d1_databases]]
binding = "DB"
database_name = "zuzu-prod"
database_id = "aa6ce9c3-1aac-424b-8b6e-accc7a790ffb"
